name: Deploy Migrations to Production

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/supabase/migrations/**'
      - '.github/workflows/deploy-migrations.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          cd apps/web
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
          supabase db push 