name: Deploy Database Migrations

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/supabase/migrations/**'
      - '.github/workflows/deploy-migrations.yml'
  workflow_dispatch:

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify environment variables
        run: |
          if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
            echo "Error: SUPABASE_ACCESS_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_PROJECT_ID }}" ]; then
            echo "Error: SUPABASE_PROJECT_ID secret is not set"
            exit 1
          fi
          echo "All required environment variables are set"

      - name: Link to Supabase project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Run database migrations
        run: |
          cd apps/web
          supabase db push --include-all
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate and update types
        run: |
          cd apps/web
          supabase gen types typescript --project-id ${{ secrets.SUPABASE_PROJECT_ID }} > src/types/database.types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Commit updated types (if needed)
        run: |
          cd apps/web
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git status --porcelain src/types/database.types.ts)" ]; then
            git add src/types/database.types.ts
            git commit -m "chore: update database types after migration deployment"
            git push
          else
            echo "No database types changes to commit"
          fi

      - name: Verify migration deployment
        run: |
          cd apps/web
          supabase db diff --use-migra --schema public
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Database migrations deployed successfully"
          else
            echo "❌ Database migration deployment failed"
            exit 1
          fi 